Sources update from the main repo
ara3d/Math3D pull request #16
Opened 2021-09-28 11:54 UTC by Vadim-Vorotilin

2021-09-28 13:30 UTC, mavimaec requested changes
Thanks for the merge @Vadim-Vorotilin ! I have a change request below for you. Also, do you think you can investigate the unit test failure?

2021-09-28 13:30 UTC, mavimaec commented on src/license.txt
> -MIT License
I think this license file got mistakenly removed in this PR

2021-09-28 14:47 UTC, vadym-vorotilin commented on src/license.txt
> -MIT License
@mavimaec  The license file is in the root folder. I think this one was a duplicate.

2021-09-28 18:06 UTC, mavimaec approved these changes
👍 good eye on the license.txt!

2021-09-29 13:42 UTC, cdiggins approved these changes
Thank you!

2021-09-29 13:51 UTC, merged